// <auto-generated />
namespace WebAppRestaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMenuItemaltercolumnNamelengthto200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMenuItemaltercolumnNamelengthto200));
        
        string IMigrationMetadata.Id
        {
            get { return "201807071753203_add MenuItem alter column Name length to 200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
